version: '3.4'

services:
  catalogdb:
    image: mongo #official name of mongo image
  
  basketdb:
    image: redis:alpine #official name of redis image

  discountdb:
    image: "postgres"  #official name of postgres image
  
  pgadmin: #pgadmin is management app for postgresql
    image: dpage/pgadmin4 #official name of pgadmin image

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes: #data storage out of the container , locate in host file system 
  mongo_data: 
  postgres_data:
  pgadmin_data:


